name: bts
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - opencv
  - moviepy
  - seaborn
  - mediapy
  - notebook
  - scipy
  - scikit-image
  - pip
  - pip:
      - tensorflow-datasets
      - hydra-core
      - omegaconf
      - h5py
      - lpips
      - dotmap
      - dotdict
